#!/usr/bin/env bash
#installs nginx and configures it on a remote server


#update packages list and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

#configure Nginx to listen to port 80
sudo sed -i 's/listen/s*80;/listen 80 default_server;/g' /etc/nginx/sites_available/default

#restart nginx without systemctl
sudo /etc/init.d/nginx restart

#create a default index page
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
