#!/usr/bin/env bash
#configure nginx server so  that /redirect_me redirect to another page


#create a new configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect_me > /dev/null <<EOF
server {
        listen 80;
        listen [::]:80;

        server_name mubarakadesina.tech;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
EOF

#enable new configuration
sudo ln -s /etc/nginx/sites_available/redirect_me /etc/nginx/sites_enabled

#restart nginx to apply new configuration
sudo service nginx restart
