#!/usr/bin/env bash
# This script configures the nginx server so that /redirect_me is redirecting to
# another page.

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Replace the location / block in the Nginx configuration file with a new block that
# redirects requests to /redirect_me to a new URL with a "301 Moved Permanently" status code
sudo sed -i '/location \/ {/{
N
s/location \/ {\n.*}/&\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }/
}' /etc/nginx/sites-available/default

sudo service nginx restart


