#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page that contains
# the string "Ceci n'est pas une page"

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i 's/# error_page 404/error_page 404/g' /etc/nginx/sites-available/default
sudo sed -i '/error_page 404/a location = /404.html {\n internal;\n }' /etc/nginx/sites-available/default
sudo sed -i '/location = \/404.html {/a root \/var\/www\/html;' /etc/nginx/sites-available/default
sudo service nginx restart

