#!/usr/bin/env bash
# configure haproxy

sudo apt-get update
sudo apt-get install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
# Configure frontend
frontend myfrontend
  bind *:80
  default_backend mybackend
# Configure backend
backend mybackend
  balance roundrobin
  server 181356-web-01 54.162.83.79:80
  server 181356-web-02 54.208.146.244:80
EOT

sudo service haproxy start
