#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg <<EOF
frontend web_front
  bind *:80
  mode http
  default_backend web_servers

backend web_servers
  mode http
  balance roundrobin
  server web-01 54.162.83.79:80 check
  server web-02 54.208.146.244:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

