#!/usr/bin/env bash
#This script display Best School 10 times
#display hi at the 9th iteration
#Using while loop

i=0
while [[ $i -le 10 ]];
        do
	        if [[ $i == 9 ]];
	                then
		                echo "Hi"
				echo "Best School"
	        else
		        echo "Best School"
	        fi
		i = $(( i + 1))
done
