#!/usr/bin/env bash
#This script iterate from 1 go 10
#display bad luck at 4th iteration
#display good luck at 8th iteration
#display Best School for others

i=1
while [[ i -le 10 ]];
        do
	        if [ $i == "4" ]
	                then
		                echo "bad luck"
	        elif [ $i == 8 ]
	                then
		                echo "good luck"
	        else
		        echo "Best School"
	        fi
	(( $i++ ))
done
